<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-br" lang="pt-br">
<head>
    <title>EMQDesenv - Aplicações</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link href="https://fonts.googleapis.com/css?family=Lovers+Quarrel|Miltonian+Tattoo|Sriracha" rel="stylesheet" /> 
    <link href="https://fonts.googleapis.com/css?family=Alex+Brush|Great+Vibes|Pinyon+Script|Tangerine" rel="stylesheet"> 
    <link rel="shortcut icon" href="emqdesenv.ico" type="image/x-icon" />
    <meta name="description" content="emqdesenv - Aplicações" />
    <meta name="keywords" content="sistemas, PHP" />
    <meta name="author" content="Edmilson Messias Quintino" />
    <link href="css/layout.css" rel="stylesheet" type="text/css" />
    
    <!-- Calendário -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />
    
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="../web/js/jquery.js"></script>
    <!-- Fim Calendário -->
    <script>
        $(document).ready(function(){
            $('<img src="../web/img/sair.png" title="Sair" height="28px" />').appendTo($('#sair'));
            $('#sair img')
                .css({
                    float:'right',
                    paddingLeft: '10px'
                });
            $('#sair img').mouseover(function(){
                $(this).css({
                    cursor:'pointer'
                })
            })
            $('#sair img').click(function(){
                $(location).attr('href','../web/sair.php');
            })
            $('#flashes').fadeOut(2000,function(){
                $(this).hide('slow');
            }) 
            $('.menu ul').css({
                position: 'absolute',
                left: '600px'
            })
        })
    </script>
</head>
<body id="page">
  <div class="SITE_ROOT" id="SITE_ROOT" >
    <div class="tail-top-right"></div>
    <div id="main">        
        <!-- header -->
      <div id="cabecalho">
          <span class="titulo">IBAD </span> &nbsp&nbsp-&nbsp <span class="cor_1" id="logo">Igreja Batista do Amor de Deus</span>
          <hr size="0.5" class="l1">
        <span id="sair"></span>
         <div class="menu" >
             <ul>
             <!--<button>-->
                   <?php 
                     $mes_=  ModelValidador::nomeMes(date('m'));
                     $menu=array('home'=>'Home','cad'=>'Cadastro de Membros','lista'=>'Ficha de Membros','relatorio'=>'Relatórios','relMensal_'=>'Movimentação');    
                     foreach($menu as $key => $item){
                       if($item == 'Movimentação'){
                          echo '<a href="index.php?pagina=relMensal&&act=cad" id="movimento" ><button class="bnt">'.$item.'</button></a>';
                       }elseif($item == 'Ficha de Membros'){
                          echo '<a href="'.Utils::createLink('cadastro',array('act'=>'lista','pag'=>0)).'" ><button class="bnt">'.$item.'</button></a>';
                          echo '<li>Fichas</li><li>Carteirinhas</li>';
                       }elseif($item == 'Cadastro de Membros'){
                          echo '<a href="'.Utils::createLink('cadastro',array('act'=>'cad','pag'=>0)).'" ><button class="bnt">'.$item.'</button></a>';
                       }else{
                          echo '<a href="'.Utils::createLink($key).'" ><button class="bnt">'.$item.'</button></a>';
                       }
                     }
                   ?>
             </ul>
          </div>
       </div>
        <!-- content -->
        <div id="content">
            <div class="wrapper">
                <div class="col-1">
                </div>
                <div class="col-2">
                    <div class="indent">
                        <?php if ($flashes): ?>
                            <ul id="flashes">
                            <?php foreach ($flashes as $flash): ?>
                                <li><?php echo $flash; ?></li>
                            <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                        <?php require $template; ?>
                    </div>
                </div>
            </div>
        </div>
     </div>
   </div>        
        <!-- footer -->
          <div  id="rodape" >
              <div class="rodape"> IBAD - Igreja Batista do Amor de Deus - Rua da PAZ, 11 - Bonsucesso - Rio de Jneiro
                      <span style="line-height:1em;"><br>©Copyright, All rights reserved</span>
              </div> 
          </div>
</body>
</html>