<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-br" lang="pt-br">
<head>
    <title>EMQDesenv - Aplicações</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link href="https://fonts.googleapis.com/css?family=Lovers+Quarrel|Miltonian+Tattoo|Sriracha" rel="stylesheet" /> 
    <link href="https://fonts.googleapis.com/css?family=Alex+Brush|Great+Vibes|Pinyon+Script|Tangerine" rel="stylesheet"> 
<link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
    <link rel="shortcut icon" href="emqdesenv.ico" type="image/x-icon" />
    <meta name="description" content="emqdesenv - Aplicações" />
    <meta name="keywords" content="sistemas, PHP" />
    <meta name="author" content="Edmilson Messias Quintino" />
    <link href="css/layout.css" rel="stylesheet" type="text/css" />
    
    <!-- Calendário -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />
    
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="../web/js/jquery.js"></script>
    <!-- Fim Calendário -->
    <script>
        $(document).ready(function(){            
            $('#sair img').mouseover(function(){
                $(this).css({
                    cursor:'pointer'
                })
            })
            $('#sair img').click(function(){
                $(location).attr('href','../web/sair.php');
            })
            $('#flashes').fadeOut(2000,function(){
                $(this).hide('slow');
            })
            //$('.menu > li a').css('color','#cc4933')
            //alert($('.menu').css('background','red'));
        })
    </script>
    <style>
        #sair img{
            float: right;
            padding-left: 10px;
        }
        .menu,
        .submenu {
            margin: 0;
            padding: 0;
        }
        .clearfix:after{
            content: '.';
            display: block;
            clear: both;
            height: 0;
            line-height: 0;
            font-size: 0;
            visibility: hidden;
            overflow: hidden;
        }
        .menu,
        .submenu {
            list-style: none;
            background: #bd9750;
        }
        .menu a{
            text-decoration: none;
            display: block;
            padding: 8px;
            color: white;
            text-shadow:#000 0px 1px 0, #999 0 -1px 0;
            font-family: sans-serif;
            font-size: 14px;
            text-transform: uppercase;
            font-weight: 700;
        }
        .menu li {
            position: relative;
        }
        .menu > li {
            float: left;
        }
        .menu li:hover .submenu{
            display: block;
        }
        .submenu {
            display: none;
            position: absolute;
            left: 598px;
            min-width: 165px;
            top: 89px;
        }
        .menu > li:hover{
            background: #875a39;
            -webkit-transition: 0.2s ease-in;
            -moz-transition: 0.2s ease-in;
            -o-transition: 0.2s ease-in;
            transition: 0.2s ease-in;
        }
        .submenu li:hover {
            background: #555;
        }
    </style>
</head>
<body id="page">
  <div class="SITE_ROOT" id="SITE_ROOT" >
    <div class="tail-top-right"></div>
    <div id="main">        
        <!-- header -->
      <div id="cabecalho">
          <span class="titulo">IBAD -&nbsp</span><span class="cor_1" id="logo">Igreja Batista do Amor de Deus</span>
          <hr size="0.5" class="l1">
        <span id="sair"><img src="../web/img/sair.png" title="Sair" height="35px" /></span>
         <div class="menu" >
             <ul class="menu">
             <!--<button>-->
                   <?php 
                     $mes_=  ModelValidador::nomeMes(date('m'));
                     $menu=array('home'=>'Home','doc'=>'Documentos','cad'=>'Cadastro de Membros','lista'=>'Ficha de Membros','relatorio'=>'Relatórios','relMensal_'=>'Movimentação');    
                     foreach($menu as $key => $item){
                       if($item == 'Movimentação'){
                          echo '<li><a href="index.php?pagina=relMensal&&act=cad" id="movimento" >'.$item.'</a></li>';
                       }elseif($item == 'Ficha de Membros'){
                          echo '<li class="sub"><a href="'.Utils::createLink('cadastro',array('act'=>'lista','pag'=>0)).'" >'.$item.'</a></li>';
                          echo '<ul class="submenu"><li><a href="#">Fichas</a></li><li><a href="#">Carteirinhas</a></li></ul>';
                       }elseif($item == 'Cadastro de Membros'){
                          echo '<li><a href="'.Utils::createLink('cadastro',array('act'=>'cad','pag'=>0)).'" >'.$item.'</a></li>';
                       }else{
                          echo '<li><a href="'.Utils::createLink($key).'" >'.$item.'</a></li>';
                       }
                     }
                   ?>
             </ul>
          </div>
       </div>
        <!-- content -->
        <div id="content">
            <?php
                if(@$_GET['index']=='sim'){
                    include_once '../web/aniversariantes.php';
                }
            ?>
            <div class="wrapper">
                <div class="col-1">
                </div>
                <div class="col-2">
                    <div class="indent">
                        <?php if ($flashes): ?>
                            <ul id="flashes">
                            <?php foreach ($flashes as $flash): ?>
                                <li><?php echo $flash; ?></li>
                            <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                        <?php require $template; ?>
                    </div>
                </div>
            </div>
        </div>
     </div>
   </div>        
        <!-- footer -->
          <div  id="rodape" >
              <div class="rodape"> IBAD - Igreja Batista do Amor de Deus - Rua da PAZ, 11 - Bonsucesso - Rio de Jneiro
                      <span style="line-height:1em;"><br>©Copyright, All rights reserved</span>
              </div> 
          </div>
</body>
</html>