var OMIE_APP_KEY = 'PUT_YOUR_APP_KEY_HERE';
var OMIE_APP_SECRET = 'PUT_YOUR_APP_SECRET_HERE';

var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;
var PedidoVendaProdutoJsonClient=function(){
	this._EndPoint="http://app.omie.com.br/api/v1/produtos/pedido/";
	this._Call=function(method,param,cb){
		var server= new XMLHttpRequest();
		server.open("POST",this._EndPoint,cb!=null);
		server.setRequestHeader("Content-Type","application/json");
		var req=JSON.stringify({call:method,app_key:OMIE_APP_KEY,app_secret:OMIE_APP_SECRET,param:(param)?param:[]});
		if(cb){
			server.onreadystatechange=this._EndCall;
			server.cb=cb;
			server.send(req);
			return server;
		}else{
			server.send(req);
			var res=JSON.parse(server.responseText);
			delete(server);
			return res;
		}
	};
	this._EndCall=function(e){
		var server=this;
		if(server.readyState!=4)
			return;
		if(server.status!=200)
			throw(new Exception("AJAX error "+server.status+": "+server.statusText));
		server.cb(JSON.parse(server.responseText));
		server.cb=null;
		delete(server);
	};
	this.IncluirPedido=function(
		pedido_venda_produto,
		_cb
	){
		return this._Call(
			"IncluirPedido",
			[
			pedido_venda_produto
			],
			(_cb)?_cb:null
		);
	};
	this.AlterarPedidoVenda=function(
		pedido_venda_produto,
		_cb
	){
		return this._Call(
			"AlterarPedidoVenda",
			[
			pedido_venda_produto
			],
			(_cb)?_cb:null
		);
	};
	this.ConsultarPedido=function(
		pvpConsultarRequest,
		_cb
	){
		return this._Call(
			"ConsultarPedido",
			[
			pvpConsultarRequest
			],
			(_cb)?_cb:null
		);
	};
	this.ListarPedidos=function(
		pvpListarRequest,
		_cb
	){
		return this._Call(
			"ListarPedidos",
			[
			pvpListarRequest
			],
			(_cb)?_cb:null
		);
	};
	this.StatusPedido=function(
		pvpStatusRequest,
		_cb
	){
		return this._Call(
			"StatusPedido",
			[
			pvpStatusRequest
			],
			(_cb)?_cb:null
		);
	};
	this.TrocarEtapaPedido=function(
		pvpTrocarEtapaRequest,
		_cb
	){
		return this._Call(
			"TrocarEtapaPedido",
			[
			pvpTrocarEtapaRequest
			],
			(_cb)?_cb:null
		);
	};
	this.cabecalho=function(){
		this.codigo_pedido=null;
		this.codigo_pedido_integracao=null;
		this.numero_pedido=null;
		this.codigo_cliente=null;
		this.codigo_cliente_integracao=null;
		this.data_previsao=null;
		this.quantidade_itens=null;
		this.etapa=null;
		this.codigo_parcela=null;
		this.qtde_parcelas=null;
		this.bloqueado=null;
		this.importado_api=null;
		this.codigo_empresa=null;
		this.codigo_empresa_integracao=null;
	};
	this.cofins_padrao=function(){
		this.cod_sit_trib_cofins=null;
		this.tipo_calculo_cofins=null;
		this.base_cofins=null;
		this.aliq_cofins=null;
		this.qtde_unid_trib_cofins=null;
		this.valor_unid_trib_cofins=null;
		this.valor_cofins=null;
	};
	this.cofins_st=function(){
		this.cod_sit_trib_cofins_st=null;
		this.tipo_calculo_cofins_st=null;
		this.base_cofins_st=null;
		this.aliq_cofins_st=null;
		this.qtde_unid_trib_cofins_st=null;
		this.valor_unid_trib_cofins_st=null;
		this.margem_cofins_st=null;
		this.valor_cofins_st=null;
	};
	this.csll=function(){
		this.aliq_csll=null;
		this.valor_csll=null;
	};
	this.departamentos=function(){
		this.cCodDepto=null;
		this.nPerc=null;
		this.nValor=null;
		this.nValorFixo=null;
	};
	this.det=function(){
		this.ide=null;
		this.produto=null;
		this.observacao=null;
		this.inf_adic=null;
		this.imposto=null;
	};
	this.ide=function(){
		this.codigo_item_integracao=null;
		this.codigo_item=null;
		this.simples_nacional=null;
		this.regra_impostos=null;
	};
	this.produto=function(){
		this.codigo_produto=null;
		this.codigo_produto_integracao=null;
		this.codigo=null;
		this.descricao=null;
		this.cfop=null;
		this.ncm=null;
		this.ean=null;
		this.unidade=null;
		this.quantidade=null;
		this.valor_unitario=null;
		this.codigo_tabela_preco=null;
		this.valor_mercadoria=null;
		this.tipo_desconto=null;
		this.percentual_desconto=null;
		this.valor_desconto=null;
		this.valor_deducao=null;
		this.valor_total=null;
	};
	this.observacao=function(){
		this.obs_item=null;
	};
	this.inf_adic=function(){
		this.peso_liquido=null;
		this.peso_bruto=null;
		this.numero_pedido_compra=null;
		this.item_pedido_compra=null;
		this.dados_adicionais_item=null;
		this.nao_movimentar_estoque=null;
		this.nao_gerar_financeiro=null;
	};
	this.imposto=function(){
		this.icms_sn=null;
		this.icms=null;
		this.icms_st=null;
		this.icms_ie=null;
		this.ipi=null;
		this.pis_padrao=null;
		this.pis_st=null;
		this.cofins_padrao=null;
		this.cofins_st=null;
		this.inss=null;
		this.csll=null;
		this.irrf=null;
		this.iss=null;
	};
	this.frete=function(){
		this.codigo_transportadora=null;
		this.codigo_transportadora_integracao=null;
		this.modalidade=null;
		this.placa=null;
		this.placa_estado=null;
		this.registro_transportador=null;
		this.quantidade_volumes=null;
		this.especie_volumes=null;
		this.marca_volumes=null;
		this.numeracao_volumes=null;
		this.peso_liquido=null;
		this.peso_bruto=null;
		this.valor_frete=null;
		this.valor_seguro=null;
		this.numero_lacre=null;
		this.outras_despesas=null;
		this.veiculo_proprio=null;
		this.icms_retido=null;
	};
	this.icms_retido=function(){
		this.vServicoTr=null;
		this.vBCRetencaoTr=null;
		this.vAliquotaRetencaoTr=null;
		this.vIcmsRetidoTr=null;
		this.cCfopTr=null;
		this.cCidadeTr=null;
	};
	this.icms=function(){
		this.cod_sit_trib_icms=null;
		this.origem_icms=null;
		this.modalidade_icms=null;
		this.perc_red_base_icms=null;
		this.base_icms=null;
		this.aliq_icms=null;
		this.valor_icms=null;
	};
	this.icms_ie=function(){
		this.base_icms_uf_destino=null;
		this.aliq_icms_FCP=null;
		this.aliq_interna_uf_destino=null;
		this.aliq_interestadual=null;
		this.aliq_partilha_icms=null;
		this.valor_fcp_icms_inter=null;
		this.valor_icms_uf_dest=null;
		this.valor_icms_uf_remet=null;
	};
	this.icms_sn=function(){
		this.cod_sit_trib_icms_sn=null;
		this.origem_icms_sn=null;
		this.aliq_icms_sn=null;
		this.valor_credito_icms_sn=null;
		this.base_icms_sn=null;
		this.valor_icms_sn=null;
	};
	this.icms_st=function(){
		this.cod_sit_trib_icms_st=null;
		this.modalidade_icms_st=null;
		this.perc_red_base_icms_st=null;
		this.base_icms_st=null;
		this.aliq_icms_st=null;
		this.margem_icms_st=null;
		this.valor_icms_st=null;
		this.aliq_icms_opprop=null;
		this.cest=null;
	};
	this.ipi=function(){
		this.cod_sit_trib_ipi=null;
		this.tipo_calculo_ipi=null;
		this.enquadramento_ipi=null;
		this.base_ipi=null;
		this.aliq_ipi=null;
		this.qtde_unid_trib_ipi=null;
		this.valor_unid_trib_ipi=null;
		this.valor_ipi=null;
	};
	this.pis_padrao=function(){
		this.cod_sit_trib_pis=null;
		this.tipo_calculo_pis=null;
		this.base_pis=null;
		this.aliq_pis=null;
		this.qtde_unid_trib_pis=null;
		this.valor_unid_trib_pis=null;
		this.valor_pis=null;
	};
	this.pis_st=function(){
		this.cod_sit_trib_pis_st=null;
		this.tipo_calculo_pis_st=null;
		this.base_pis_st=null;
		this.aliq_pis_st=null;
		this.qtde_unid_trib_pis_st=null;
		this.valor_unid_trib_pis_st=null;
		this.margem_pis_st=null;
		this.valor_pis_st=null;
	};
	this.inss=function(){
		this.aliq_inss=null;
		this.valor_inss=null;
	};
	this.irrf=function(){
		this.aliq_irrf=null;
		this.valor_irrf=null;
	};
	this.iss=function(){
		this.base_iss=null;
		this.aliq_iss=null;
		this.valor_iss=null;
		this.retem_iss=null;
	};
	this.infoCadastro=function(){
		this.dInc=null;
		this.hInc=null;
		this.uInc=null;
		this.dAlt=null;
		this.hAlt=null;
		this.uAlt=null;
		this.cImpAPI=null;
	};
	this.informacoes_adicionais=function(){
		this.codigo_categoria=null;
		this.codigo_conta_corrente=null;
		this.numero_pedido_cliente=null;
		this.numero_contrato=null;
		this.contato=null;
		this.dados_adicionais_nf=null;
		this.consumidor_final=null;
		this.utilizar_emails=null;
		this.enviar_email=null;
		this.codVend=null;
		this.codProj=null;
		this.outros_detalhes=null;
	};
	this.outros_detalhes=function(){
		this.cNatOperacaoOd=null;
		this.cIndicadorOd=null;
		this.dDataSaidaOd=null;
		this.cHoraSaidaOd=null;
		this.cCnpjCpfOd=null;
		this.cEnderecoOd=null;
		this.cNumeroOd=null;
		this.cComplementoOd=null;
		this.cBairroOd=null;
		this.cEstadoOd=null;
		this.cCidadeOd=null;
	};
	this.lista_parcelas=function(){
		this.parcela=null;
	};
	this.parcela=function(){
		this.numero_parcela=null;
		this.valor=null;
		this.percentual=null;
		this.data_vencimento=null;
		this.quantidade_dias=null;
	};
	this.ListaNfe=function(){
		this.numero_lote=null;
		this.status_lote=null;
		this.recibo=null;
		this.contingencia=null;
		this.numero_nfe=null;
		this.status_nfe=null;
		this.chave_nfe=null;
		this.protocolo=null;
		this.tipo=null;
		this.data_emissao=null;
		this.hora_emissao=null;
		this.data_fatura=null;
		this.hora_fatura=null;
		this.data_saida=null;
		this.hora_saida=null;
		this.mensagens=null;
		this.xml_distr=null;
		this.danfe=null;
	};
	this.mensagens=function(){
		this.cCodigo=null;
		this.cDescricao=null;
		this.cCorrecao=null;
	};
	this.observacoes=function(){
		this.obs_venda=null;
	};
	this.pedido_venda_produto=function(){
		this.cabecalho=null;
		this.departamentos=null;
		this.frete=null;
		this.informacoes_adicionais=null;
		this.lista_parcelas=null;
		this.observacoes=null;
		this.det=null;
		this.total_pedido=null;
		this.infoCadastro=null;
	};
	this.total_pedido=function(){
		this.base_calculo_icms=null;
		this.base_calculo_st=null;
		this.valor_pis=null;
		this.valor_cofins=null;
		this.valor_csll=null;
		this.valor_icms=null;
		this.valor_st=null;
		this.valor_inss=null;
		this.valor_IPI=null;
		this.valor_ir=null;
		this.valor_iss=null;
		this.valor_deducoes=null;
		this.valor_descontos=null;
		this.valor_mercadorias=null;
		this.valor_total_pedido=null;
	};
	this.pedido_venda_produto_response=function(){
		this.codigo_pedido=null;
		this.codigo_pedido_integracao=null;
		this.codigo_status=null;
		this.descricao_status=null;
		this.numero_pedido=null;
	};
	this.pvpConsultarRequest=function(){
		this.codigo_pedido=null;
		this.codigo_pedido_integracao=null;
		this.numero_pedido=null;
	};
	this.pvpConsultarResponse=function(){
		this.pedido_venda_produto=null;
	};
	this.pvpListarRequest=function(){
		this.pagina=null;
		this.registros_por_pagina=null;
		this.apenas_importado_api=null;
		this.ordenar_por=null;
		this.ordem_descrescente=null;
		this.filtrar_por_data_de=null;
		this.filtrar_por_data_ate=null;
		this.filtrar_apenas_inclusao=null;
		this.filtrar_apenas_alteracao=null;
		this.filtrar_por_cliente=null;
		this.etapa=null;
	};
	this.pvpListarResponse=function(){
		this.pagina=null;
		this.total_de_paginas=null;
		this.registros=null;
		this.total_de_registros=null;
		this.pedido_venda_produto=null;
	};
	this.pvpStatusRequest=function(){
		this.codigo_pedido=null;
		this.codigo_pedido_integracao=null;
	};
	this.pvpStatusResponse=function(){
		this.codigo_pedido=null;
		this.codigo_pedido_integracao=null;
		this.numero_pedido=null;
		this.etapa=null;
		this.cancelada=null;
		this.faturada=null;
		this.ambiente=null;
		this.valor_total_pedido=null;
		this.ListaNfe=null;
	};
	this.pvpTrocarEtapaRequest=function(){
		this.codigo_pedido=null;
		this.codigo_pedido_integracao=null;
		this.numero_pedido=null;
		this.etapa=null;
	};
	this.pvpTrocarEtapaResponse=function(){
		this.codigo_pedido=null;
		this.codigo_pedido_integracao=null;
		this.numero_pedido=null;
		this.codigo_status=null;
		this.descricao_status=null;
	};
	this.omie_fail=function(){
		this.code=null;
		this.description=null;
		this.referer=null;
		this.fatal=null;
	};
};
module.exports = PedidoVendaProdutoJsonClient;