<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script>
   $(document).ready(function(){          
      var original=$('.foto :hidden').val();
      $('#image-holder img').attr('src', original);
      $('#fileUpload').change(function(){
         $('.foto :hidden').attr('value','');
      })  
      $('.ed').css('marginTop','5px');
      $('.cart').css({
          marginLeft:'5px',
          border: '1px solid gray',
          width: '40px',
      });
      $(':checkbox').prop('checked',false);
      $('.cart').click(function(){
          ids = [];
          $.each($(":checkbox"), function(){
                if($(this).is(":checked")){
                    ids.push($(this).attr('name'));                      
                        $( "#dialog-confirm" ).dialog({
                          resizable: false,
                          modal: true,
                          buttons: {
                            "SIM": function() {
                              $( this ).dialog( "close" );
                              $(location).attr('href','index.php?pagina=documentos&act=carteirinha&ids='+ids+'&lista=sim&nome='+nome+'');
                            },
                            "NÂO": function() {
                                $( this ).dialog( "close" );
                                var link = "../web/carteirinha.php?ids="+ids+"&act=carteirinha";
                                window.open(link,'targetWindow','toolbar=no,location=no,status=no,menubar=no,scrollbars=yes,resizable=yes,width=1024,height=740');
                              return false;
                            }
                          }
                        })
                }
          })
      })
      $('.bntcart').click(function(){
          $(location).attr('href','index.php?pagina=documentos&act=carteirinha&ids='+ids+'');        
      })
      $('.certBatismo').mouseover(function(){
          $(this).css({
              cursor: 'pointer'
          });
          $(this).click(function(){
              id=$(this).attr('name');
              act='cert';
              var link = "../web/certificado.php?id="+id+"&act="+act+"";
              window.open(link,'targetWindow','toolbar=no,location=no,status=no,menubar=no,scrollbars=yes,resizable=yes,width=1024,height=740');
          })
      })
      $('.procura').bind('mouseover', function(){
          $(this).css({
              cursor: 'pointer'
          })
      })
      $('.procura img').bind('click', function(){
          var nome=$('.bsc').val();
            if(nome){
                $(location).attr('href','index.php?pagina=cadastro&act=lista&pag=0&busca=1&nome='+nome+'');
            }
      })
      $('.procura').keyup(function(e){
            var code = e.which; // recommended to use e.which, it's normalized across browsers
            if(code==13)e.preventDefault();
            if(code==13||e.keyCode==13){
                var nome=$('.bsc').val();
                if(nome){
                    $(location).attr('href','index.php?pagina=cadastro&act=lista&pag=0&busca=1&nome='+nome+'');
                }
            } 
      })
      $('.procura').prepend('<button><span>Aniversariantes</span></button>')
      $('.procura button').css({
          marginRight: '5px',
          cursor: 'pointer',
          fontFamily: 'cursive',
          textShadow: '4px 4px 4px black',
          background: '#cacb8d',
          borderRadius: '5px',
          fontSize: '18px',
          color: 'white'
      })
      $('.procura button').mousedown(function(){
        $('.procura button span').css({
          position: 'relative',
          top: '-2px',
          left: '-2px'
        })
        $(this).mouseup(function(){
            $('.procura button span').css({
                position: 'relative',
                top: '1px',
                left: '1px'
            })
            $(location).attr('href','index.php?pagina=aniversariantes')
        })
      })
   })
</script>
<style>
    #rodape, #dialog-confirm{
        display: none;
    } 
    .fotoFicha{
        background: #ccc;
    }
    .procura{
        position: relative;
        top: 3px;
        padding-right: 5px;
    }
</style> 
<div  class="conteudo" >
    <div id="dialog-confirm" title="CARTEIRINHA">Deseja Selecionar Mais Membros?</div>   
    <div class="cadastro">
        <?php if($act=='lista'):?>
               <?php                   
                  $titulos=array('Nome','E-mail','Tel.','Nascimento','Endereço','Batismo','Membro desde','Estado Civil','Conjuge','Igreja do Batismo');
                  echo '<div class=paginacao>';
                    echo '<span class="procura"><input class="bsc" type="text" name="busca" /> <img src="imagens/lupa.png" height=18px title="Buscar"/></span>';
                     $pag = ($x/4)+1;
                    echo 'Páginas ';
                    echo $pag .' de ';
                    echo ceil(count($lista)/4);
                    echo '<span class="bntcart"></span>';
                  echo '</div>';
                  if(($x/4)+1 == ceil(count($lista)/4)){
                     $class2='class=disabled';
                  }else{
                     $class2='title="AVANÇAR"';
                  }
        echo '<fieldset class=lista><legend><a href='.Utils::createLink('cadastro',array('act'=>'lista','pag'=>$x-4,'nome'=>$nome)).' '.$class.' ><< </a> FICHA DE MEMBROS <a href='.Utils::createLink('cadastro',array('act'=>'lista','pag'=>$x+4,'contador'=>count($lista),'nome'=>$nome)).' '.$class2.'> >> </a></legend>';
        echo '<script>
                if(nome==null){
                    var nome="'.$nome.'";
                }
             </script>';
           echo '<table cellspacing=0 border=1>';
            echo '<tr><td colspan=7 class=divisao>&nbsp</td><tr>';
                  $cont=0;
                  foreach($lista as $keys => $item){
                     $cont++;
                    if($cont > $x && $cont < $y){
                       if($item->getnome()){
                        echo '<tr><td class="nome">'.$titulos[0].' </td><td class=dados colspan=3>&nbsp'.$item->getnome().' </td><td class=nome2>'.$titulos[3].' </td><td class=dados>&nbsp'.ModelValidador::data($item->getdt_nascimento()).'</td>';
                    if(substr($item->getfoto(),0,7)=='imagens'){
                        echo '<td class=fotoFicha width="250" height="50" rowspan="5" align="center">';
                      echo '<span><img title="'.$item->getnome().'" src="'.$item->getfoto().'" /></span><br><a href="../web/index.php?pagina=cadastro&act=cad&pag=0&id='.$item->getid().'" ><img class="ed" src="../web/img/edicao.ico" height=15px title="Editar dados"/></a><div class="cart" title="Selecione para ver a carteirinha"><img src="../web/img/cracha.ico" height=15px /><input type="checkbox" name="'.$item->getid().'"/></dic>';
                    echo '</td>';
                    }
                    echo '</tr>';
                       }
                       if($item->gettel()||$item->getcel()||$item->getemail()){
                          if($item->getemail()){
                             $colspan=2;
                          }else{
                             $colspan=5;
                          }
                        echo '<tr><td class=nome >'.$titulos[2].' </td><td class=dados colspan='.$colspan.'>&nbsp'.$item->gettel();
                        if($item->gettel() && $item->getcel()){echo ' / ';};
                        echo $item->getcel().'</td>';
                       if($item->getemail()){
                        echo '<td class=nome>'.$titulos[1].' </td><td class=dados_ colspan=2>&nbsp'.$item->getemail().'</td></tr>';
                       }
                       }
                       if($item->getestcivil()){
                          if(strstr($item->getestcivil(),'d',true)=="Casa" || strstr($item->getestcivil(),'d',true)=="CASA"){
                             $colspan=1;
                          }else{
                             $colspan=5;
                          }
                          echo '<tr><td class=nome>'.$titulos[7].' </td><td class="dados" colspan='.$colspan.'>&nbsp'.$item->getestcivil().'</td>';
                          if(strstr($item->getestcivil(),'d',true)=='Casa' || strstr($item->getestcivil(),'d',true)=='CASA'){
                          echo '<td class=nome2>'.$titulos[8].' </td><td class=dados colspan=3>&nbsp'.$item->getconjuge().'</td></tr>';
                          }
                       }
                       if($item->gettipo()){
                        echo '<tr><td class=nome>'.$titulos[4].' </td><td class=dados colspan=5>&nbsp'.$item->gettipo().' '.$item->getendereco().', '.$item->getnumero();
                       }
                       if($item->getcomplemento()){
                         echo ' - '.$item->getcomplemento();
                       }
                       if($item->getbairro()){
                        echo ' - '.$item->getbairro();
                       }
                       if($item->getcidade()){
                          echo '<br>&nbsp'.$item->getcidade();
                       }
                       if($item->getcep()){
                          echo ' - CEP'.$item->getcep();
                       }
                       if($item->getdt_batismo() && $item->getdt_batismo()!='0000-00-00'){
                        echo '<script> var id='.$item->getid().'; </script>';
                        echo '<tr><td class="nome col1">'.$titulos[5].' </td><td title="Clique para ver o certificado." class="dados col2, certBatismo" name="'.$item->getid().'">&nbsp'.ModelValidador::data($item->getdt_batismo()).'</td><td class="nome3 col3">'.$titulos[9].'</td><td class="dados col4">&nbsp'.$item->getigbatismo().'</td><td class="nome2 col5">'.$titulos[6].' </td><td class="dados col6">'.ModelValidador::membroDesde($item->getdt_ingresso()).'</td></tr>';
                       }
                     echo '<tr><td colspan=7 class=divisao>&nbsp</td><tr>';
                    }elseif($cont > $y){
                       break;
                    }
                  }
                       echo '</table>';
      echo '</fieldset>';
      
         elseif($act=='cad'):
            if(array_key_exists("id", $_GET)){
                $search->setId($_GET['id']);
                $search->setorder(null);
            }
            $dados_=$dao->encontre($search);
            $dados=$dados_[array_keys($dados_)[0]];
            //$dados= get_class_vars($dados);
        ?>
        <fieldset class=cadMembros>
            <legend>CADASTRO DE MEMBROS</legend>
             <form class="font_1" enctype="multipart/form-data"  id="cadastro" action="../paginas/add.php?act=cad" method="POST" >
         <table>
             <?php 
             foreach($variaveis as $keys => $item){
                if(!$search->getid()){
                    $classe=null;
                }else{
                    $classe='get'.$item;
                }
                echo '<input type=hidden name=id value="';
                    if($classe){ 
                        echo $dados->getid();
                    }
                echo '">';
                echo '<input type=hidden name=tabela value="lt_membros" />';
                 if($item=='email'){
                    echo "<tr><td align=\"right\"> $keys: </td><td><input type=\"text\" name=\"".$item."\" size=\"40\" value=";
                    if($classe){
                        echo $dados->getemail();
                    }
                    echo " ></td></tr>";
                 }elseif(substr($item,0,2)=='dt'){
                    if($classe){
                        if(ModelValidador::data($dados->$classe())=='//'){
                           $data_=null;
                        }else{
                           $data_= ModelValidador::data($dados->$classe());
                        }
                    }else{
                        $data_=null;
                    }
                    echo "<tr><td align=\"right\">$keys: </td><td><input type=\"text\" name=\"".$item."\" size=\"40\" value='".$data_."' ></td></tr>";
                 }elseif($item=='sexo'){
                    if($dados->getsexo()=='Masculino'){
                       $masculino='checked';
                       $femenino=null;
                    }elseif($dados->getsexo()=='Femenino'){
                       $femenino='checked';
                       $masculino=null;
                    }else{
                       $masculino=$femenino=null;
                    }
                    echo "<tr><td align=right>$keys: </td><td id=sexo align=center><input type=radio name=sexo value=Masculino $masculino> Masculino ";
                    echo "<input type=radio name=sexo value=Femenino $femenino> Femenino </td></tr>";
                 }else{
                    echo "<tr><td align=\"right\">$keys: </td><td><input type=\"text\" name=\"".$item."\" size=\"40\" value='";
                    if($classe){
                        echo $dados->$classe();
                    }
                    echo "' ></td></tr>";
                 }
             }
             ?>
            <input type="hidden" name="MAX_FILE_SIZE" value="3000000" />
             <div class="foto">
                  <div id="wrapper" style="margin-top: 20px;">
                     <input id="fileUpload" name="foto" multiple="multiple" type="file" title="Inserir foto"/> 
                     <div id="image-holder"><img class="thumb-image" src="" alt="Inserir Foto" /></div>
                     <input type="hidden" name="foto" value="<?php if($classe){echo $dados->getfoto();} ?>"/>
                     <br><br>
                     Inserir Certificado de Batismo:
                    <div><input name="certificado" type="file" title="Inserir o certificado"/></div>
                  </div>
             </div>            
            <tr><td></td><td align="right">
                    <button>GRAVA</button>
            <!--<input type="submit" value="GRAVA">-->
               &nbsp<input type="reset" value="LIMPA"></td></tr>
         </table>
             </form>
            <span class="info">* campos obrigatórios</span>
        </fieldset>
        <?php endif; ?>
    </div>
</div>