<link href="https://fonts.googleapis.com/css?family=Kelly+Slab|Medula+One|Stint+Ultra+Condensed|Tulpen+One|Unica+One" rel="stylesheet"> 
<style>  
    .carteirinha{
        /*font-family: 'Kelly Slab';
        font-family: 'Unica One';*/
        font-family: 'Medula One';
        /*font-family: 'Tulpen One';
        font-family: 'Stint Ultra Condensed';*/
        font-size: 25px;
    }
</style>
<script>
    $(document).ready(function(){
        $('.certificado, certificadoVerso').hide();
        var font = '25px';
        var familia = 'Pacifico';
        var familia2 = 'Courgette';
        var familia3 = 'Great Vibes';
        var familia4 = 'Tangerine';
        var familia5 = 'Alex Brush';
        var familia6 = 'Pinyon Script';
        $('.msg').css({
            position: 'absolute',
            top: '100px'
        })
        $('.certificado').append('<img src="../web/img/certificado Frente.png" />')
        $('.certificado img').css({
            height: '500px',
            margin: '-68px 18%'
        })   
        $('.membro').css({
            position: 'relative',
            top: '210px',
            left: '330px',
            fontSize: '33px',
            width: '480px',
            textAlign: 'center',
            fontFamily: familia5,
            fontWeight: '900'
        }) 
        $('.pai').css({
            position: 'relative',
            top: '255px',
            left: '220px',
            fontSize: font,
            width: '300px',
            textAlign: 'center',
            fontFamily: familia3,
            fontWeight: '700'
        }) 
        $('.mae').css({
            position: 'relative',
            top: '223px',
            left: '180px',
            fontSize: font,
            textAlign: 'center',
            fontFamily: familia3,
            fontWeight: '700'
        })
        $('.dt_batismo').css({
            position: 'relative',
            top: '338px',
            left: '285px',
            fontSize: font,
        })
        $('.certificado img').mouseover(function(){
            $('.msg').text('Clique para ver o verso.').css('color','red');
            $(this).mouseout(function(){
                $('.msg').text('');
            })
            $(this).css({
                cursor: 'pointer'                
            })
            $(this).click(function(){
                $(location).attr('href','index.php?pagina=documentos&id='+id+'&act=verso');
            })
        })
        $('.certificadoVerso').append('<img width=700px src="../web/img/'+batizado+'Beca.jpg" />')
        $('.certificadoVerso').append('<img src="../web/img/certificado (ATRAS)branco.png" />')
        if(act=='carteirinha'){
        //alert('oi');
            $('.carteirinha table').css({
                //border: 'solid green',
                margin: 'auto',
                width: '600px',
                background: 'white'
            })
            $('.carteirinha').css({
                height: '600px',                
                overflow: 'scroll',
            })
            $('caption').css({
                fontSize: '40px',
                transform: 'caption'
            })
            $('th, td').css({
                fontSize: '30px'
            })
            /*$('.carteirinha').append('<img src="../web/img/carteirinha.png" height="300px" />')
            $('.carteirinha img').css({
                position: 'absolute',
                left: '15%',
                top: '9%',
            })
            $('.foto1').append('<img src="'+foto1+'" height="100px" width="80px" />')
            $('.foto1 img').css({
                margin: '15px 167px'
            })
            $('.nome1').text(nome1).css({
                position: 'relative',
                zIndex: '1',
                margin: '-10px 240px'
            })
            $('.pai1').text(pai1).css({
                position: 'relative',
                zIndex: '1',
                margin: '10px 240px'
            })
            $('.mae1').text(mae1).css({
                position: 'relative',
                zIndex: '1',
                margin: '-39px 410px'
            })
            $('.dt_nascimento1').text(dt_nascimento1).css({
                position: 'relative',
                zIndex: '1',
                margin: '54px 240px'
            })
            $('.estcivil1').text(estcivil1).css({
                position: 'relative',
                zIndex: '1',
                margin: '-84px 420px'
            })
            $('.dt_ingresso1').text(dt_ingresso1).css({
                position: 'relative',
                zIndex: '1',
                margin: '97px 238px'
            })
            $('.dt_batismo1').text(dt_batismo1).css({
                position: 'relative',
                zIndex: '1',
                margin: '-126px 415px'
            })
            $('.funcao1').text(funcao1).css({
                position: 'relative',
                zIndex: '1',
                margin: '128px 260px'
            })
            $('.rg1').text(rg1).css({
                position: 'relative',
                zIndex: '1',
                margin: '-158px 430px'
            })
            $('.endereco1').text(endereco1).css({
                position: 'relative',
                zIndex: '1',
                width: '310px',
                margin: '-279px 670px',
                fontSize: '21px'
            })
            $('.ano1').text(ano1).css({
                position: 'relative',
                zIndex: '1',
                width: '310px',
                margin: '382px 633px',
                fontSize: '15px',
                fontFamily: 'sans',
                fontWeight: '900',
                color: '#870000'
            })
            $('.ano2').text(ano2).css({
                position: 'relative',
                zIndex: '1',
                width: '310px',
                margin: '-400px 705px',
                fontSize: '15px',
                fontFamily: 'sans',
                fontWeight: '900',
                color: '#870000'
            })
            $('.ano3').text(ano3).css({
                position: 'relative',
                zIndex: '1',
                width: '310px',
                margin: '382px 775px',
                fontSize: '15px',
                fontFamily: 'sans',
                fontWeight: '900',
                color: '#870000'
            })
            $('.ano4').text(ano4).css({
                position: 'relative',
                zIndex: '1',
                width: '310px',
                margin: '-400px 850px',
                fontSize: '15px',
                fontFamily: 'sans',
                fontWeight: '900',
                color: '#870000'
            })
            $('.ano5').text(ano5).css({
                position: 'relative',
                zIndex: '1',
                width: '310px',
                margin: '382px 925px',
                fontSize: '15px',
                fontFamily: 'sans',
                fontWeight: '900',
                color: '#870000'
            })*/
       }
        $('.certificadoVerso img').wrap('<div class=beca></div>')
        $('.beca').css({
            position: 'absolute'
        })
        $('.certificadoVerso img, .certificadoVerso .beca').css({
            height: '500px',
            margin: '30px 100px'
        }) 
        $('.certificadoVerso img').mouseover(function(){
            $('.msg').text('Clique para virar.').css('color','red');
            $(this).mouseout(function(){
                $('.msg').text('');
            })
            $(this).css({
                cursor: 'pointer'                
            })
            $(this).click(function(){
                $(location).attr('href','index.php?pagina=documentos&id='+id+'&act=cert');
            })
        })
        $('.membro').text(nome);
        $('.pai').text(pai);
        $('.mae').text(mae);
        $('.certificado, certificadoVerso').fadeIn(200);       
        $('#certificado').click(function(){
            if(act=='carteirinha'){
                //alert('oi');
                /*for(var i;i > $(':checkbox').length;i++){
                    alert($(':checkbox')[0].checked(false));die;
                }*/
                var ids = [];
                //alert(arr);
                $(':checkbox:checked').each(function(i){
                    ids.push($(this).attr('name'));
                })
                    //alert(arr);
                var link = "../web/carteirinha.php?ids="+ids+"&act="+act+"";
               window.open(link,'targetWindow','toolbar=no,location=no,status=no,menubar=no,scrollbars=yes,resizable=yes,width=1024,height=740'); 
            }else{
                var link = "../web/certificado.php?id="+id+"&act="+act+"";
                window.open(link,'targetWindow','toolbar=no,location=no,status=no,menubar=no,scrollbars=yes,resizable=yes,width=1024,height=740');
            }
        })
    })
</script>
<div class="imprime">
        <button id='certificado' >IMPRIMIR</button>
</div>
<div class="conteudo" id="printable">
<?php if($act=='cert'): ?>    
    <div class="certificado">
        <div class="membro"></div>
        <div class="pai"></div>
        <div class="mae"></div>
        <div class="dt_batismo"><?= $dd.$esp.$mm.$esp.$aa ?></div>
    </div>
    <div class="msg"></div>
<?php elseif($act=='verso'): ?>
    <div class="certificadoVerso">
        <div></div>
    </div>
    <div class="msg"></div>
<?php elseif($act=='carteirinha'): ?>
    <?php $ident=explode(',',$ids); ?>
    <div class="carteirinha">
        <table border="1" cellspacing="0" cellpadding="5">
            <caption>Selecione os membros para emissão das carteirinhas:</caption>
            <tr><th colspan="2">MEMBROS</th><th>SELECIONE</th></tr>
            <?php foreach($model as $lista){ ?>
            <tr><td align="center"><img src="<?= $lista->getfoto() ?>" height="60px"/></td><td align="center"><?= mb_strtoupper($lista->getnome(),'utf-8') ?></td><td align="center"><input type="checkbox" name="<?= $lista->getid() ?>" 
        <?php 
           if(in_array($lista->getid(),$ident)) echo "checked" 
        ?> /></td></tr>
            <?php 
                } 
            ?>
        </table>
    </div>
    <div class="msg"></div>
<?php endif; ?>
</div>

