<style>
    #tipo{
       display: none;
    }
    #mov{
        width: 560px;
        margin: 20px auto;
        background: rgba(0, 0, 0, 0.2);
        text-shadow: 1px 1px white;
        font-weight: 700;
    }
    caption{
        font-size: 20px;
    }
    .rel{
        width: 560px;
    }
    /*tr:nth-child(even) {background: gray}
    tr:nth-child(odd) {background: #FFF}*/
</style>
<script>
    $(document).ready(function(){   
        
        var palavras = new Array('SALDO','TOTAIS');
        $.each(palavras, function(index, value){
           $('tr:contains('+value+')').css('background','darkgray')
        })
        $('.rel tr:even').css('background','darkgray')
        
        $('#tipo').hide();
        $('#comprovante').hide();
        $('#movimentacao').change(function(){
           var mov=$('#movimentacao').val();
           if(mov=='entrada'){
              $('#tipo').show();
              $('#comprovante').hide();
           }else if(mov=='saida'){
                $('#tipo').hide()
                $('#comprovante').show()
                $('#descricao :input').remove()
                $('#descricao').text('')
                $('#descricao').append('<input required type="text" name="descricao" size="50" />')
           }
        })
        $('#tipo').click(function(){
           var x=$("input:checked").val();
           if(x=='oferta'){
              $('#descricao')
                 .text('OFERTA');
              $('#descricao').val('OFERTA');
           }else if(x=='dizimo'){
              var y = membros;
              y = (y.split(','));
              var b='<select name=descricao>'; 
              var c;
                 for(i=0;i<(y.length);i++){
                    c +='<option size="500" value=\''+y[i]+'\'>'+y[i]+'</option>';
                 } 
              var d='</select>';
              $('#descricao')
                 .html(b+c+d);
           }
        }) 
        $(':button, :reset, :submit').bind('mouseover', function(){
            $(this).css({
                cursor: 'pointer',
                background: 'gray',
                color: 'white'
            })      
        })
        $(':button, :reset, :submit').css({
                background: 'silver',
                color: 'black',
                padding: '0 10px'
        })  
        $(':button, :reset, :submit').bind('mouseleave',function(){
            $(this).css({
                background: 'silver',
                color: 'black'
            })
        }) 
        $(':file').change(function(){
            var ext=$(this).val().split('.');
            if(ext[1] != 'jpg'){
                alert('Selecione somente arquivo em jpg.');
                $(this).val(null)
            }
        })
        if(act=='cad'){
            $('.imprime').hide()
        }
        $('#comp').mouseover(function(){
            $(this).css({
                cursor: 'pointer'
            })
        })
        $('#comp a').click(function(){
            if(!$(this).attr('href')){
                alert('Não existe comprovante.');
                return false;
            }
        })
    })
</script>
<?php
    require_once '../dao/RelBusca.php';
    $variaveis=array('dt','descricao','entrada','saida','diz_ofe');
    $act =$_GET['act']; 
    $dao = new Dao();
    $model = new Model();
    $search = new RelBusca();
    $search->settabela('saldo');
    foreach($dao->encontre($search) as $tudo);
    if($act=='cad'){
        $ano = $tudo->getano();
        if($tudo->getmes()=='dezembro'){
            $mes='janeiro';
            $ano=$ano+1;
        }else{
            $mes = ModelValidador::nomeMes(ModelValidador::numeroMes($tudo->getmes())+1);
        }
    }else{
      $mes=ModelValidador::nomeMes((substr($_GET['mes'],0,2)));
      $ano='20'.substr($_GET['mes'],-2,2);
      $data_=explode("/", $_GET['mes']);
    }
              
    @$continua=$_GET['continua'];
    @$conclui=$_GET['conclui'];
    $link="../web/resumo.php?mes=".ModelValidador::numeroMes(ModelValidador::tirarAcento($mes))."&ano=$ano";
?>
<script>
   var link='<?= $link; ?>';
   var act='<?= $act; ?>';
</script>
   
<div class="imprime">
        <button id='imprimeRel' >IMPRIMIR</button>
</div>
     <div class="conteudo">
         <?php 
            if($act=='cad'):
               $search = new RelBusca();
               $search->settabela('lt_membros');
               $search->setorder('nome');
               $membros=$dao->encontre($search);
               $lista = "'";
               foreach($membros as $membro){
                  $lista .= mb_strtoupper($membro->getnome().',','UTF-8');
               }
               $lista .="'";
               echo '<script>
                        var membros='.$lista.';
                     </script>';               
         ?>
         <form enctype="multipart/form-data" class="font_1" id="cadastro" action="../paginas/add.php?act=rel" method="POST" >
         <table class="notprint" id="mov">
                 <caption>MOVIMENTO DO MÊS DE <?= mb_strtoupper($mes,'UTF-8')?> DE <?= $ano ?></caption>
                 <tr><td align="right">DIA: </td><td><input autofocus required type="text" name="dia" size="1" maxlength="2"/></td></tr>
                 <tr>
                     <td align="right">MOVIMENTAÇÃO: </td>
                     <td>
                     <select required id="movimentacao" name="movimentacao" >
                         <option></option>
                         <option value="entrada">ENTRADA</option>
                         <option value="saida">SAÍDA</option>
                     </select>
                     </td>
                     <td>
                     <input type="hidden" name="mes" value="<?= $mes; ?>" />
                     <input type="hidden" name="ano" value="<?= $ano; ?>" />
                     <span id="tipo" >
                        <input type="radio" name="tipo" value="dizimo"/>Dízimo
                        <input type="radio" name="tipo" value="oferta"/>Oferta
                     </span>                     
                        <span id="comprovante">
                            <input multiple="multiple" type="file" name="comprovante" />
                        </span>
                     </td>
                 </tr>
                 <tr><td align="right">DESCRIÇÃO: </td><td id="descricao" colspan="2" ><input required type="text" name="descricao" size="50" /></td></tr>
                 <tr><td align="right">VALOR: </td><td><input required type="text" name="valor" size="15" /></td></tr>
                 <br>
                 <tr>
                 <input name='mesAno' type='hidden' value='<?= ModelValidador::numeroMes($mes).'/'.$ano; ?>' >
                     <td></td><td></td><td align="right"><input type="reset" value="LIMPA">&nbsp<input type="submit" value="GRAVA"><br><br><input id="conclui" type="button" value="CONCLUI" ></td>
                 </tr>
         </table>
         </form>
         <?php elseif($act=='rel'): 
             $somaEntrada=0;
             $somaSaida=0;
             $mesAnterior=ModelValidador::nomeMes($_GET['mes']-1);
             if($_GET['mes']==1){
                $mesAnterior='dezembro';
                $ano=$ano-1;
             }
             $search=new RelBusca();
             $search->setano($ano);
             $search->settabela('saldo');
             $search->setmes(strtolower(ModelValidador::tirarAcento($mesAnterior)));
             $dados=$dao->encontre($search);
             if(!$dados){
                echo 'Relatório inexistente';
                die;
             }
             
             foreach($dados as $saldomes); 
             $saldo=$saldoAnterior=($saldomes->getsaldo()); 
             $search->setmes(ModelValidador::numeroMes(ModelValidador::tirarAcento($mes)));
             if($_GET['mes']==1){
                $ano=$ano+1;
             }
             $search->settabela($ano);
             $search->setorder('dt');
             $search->setano(null);
             $relatorios=$dao->encontre($search); 
             if(!$relatorios && $conclui != 1){
                  echo 'Relatório do mês de '.$mes.' é inexistente.';
                  die;
             } 
             foreach($relatorios as $datas); 
          ?>
       <div class="rel" >
         <table border="1" cellspacing="0" class="rel">
             <tr><th colspan="<?= count($variaveis) ?>2" align="center">MOVIMENTO FINANCEIRO DO MÊS - <?= mb_strtoupper($mes,'UTF-8').'('.$ano.')'; ?></th></tr>
             <tr>
                 <?php 
                    foreach($variaveis as $variavel){
                        if($variavel=='dt'){
                           echo '<th>';
                           echo 'DIA';
                        }elseif($variavel=='diz_ofe'){
                           echo '<th>';
                           echo 'DÍZIMO/<br>OFERTA';
                        }elseif($variavel=='descricao'){
                           echo '<th width="100%">';
                           echo 'DESCRIÇÃO';
                        }else{
                           echo '<th>';
                           echo strtoupper($variavel);
                        }
                      echo '</th>';
                    }
                      echo '<th>SALDO</th>';
                 ?>
             </tr>
                     <?php 
                       echo '<tr><td align=center>01</td><td>SALDO ANTERIOR</td><td align=center></td><td align=center></td><td align=center></td><td align=right>'.number_format($saldo,'2',',','.').'</td></tr>';
                       $resumo=array();
                       $nomesDupl=array();
                       $nomesdiz=array();
                       foreach($relatorios as $dizimistas){
                           if($dizimistas->getdiz_ofe()=='diz'){
                                if(array_key_exists($dizimistas->getdescricao(), $nomesdiz)){
                                    $nomesdiz[$dizimistas->getdescricao()]=$nomesdiz[$dizimistas->getdescricao()]+$dizimistas->getentrada();
                                    $dataEntrega[$dizimistas->getdescricao()]=$dizimistas->getdt();
                                    if(!in_array($dizimistas->getdescricao(), $nomesDupl))
                                    $nomesDupl[]=$dizimistas->getdescricao();
                                }else{
                                    $nomesdiz[$dizimistas->getdescricao()]=$dizimistas->getentrada();
                                }
                           }
                           $nomesD=array_unique($nomesDupl);
                       }
                       foreach($relatorios as $relatorio){
                         echo '<tr><tr></tr>';
                          foreach($variaveis as $item){
                           $getnome="get$item";
                             if(($relatorio->$getnome() != 0 && is_numeric($relatorio->$getnome()))||$item == 'dt'){
                                 if(!in_array($relatorio->getdescricao(),$nomesDupl)){
                                    if($item == 'dt'){  
                                       echo '<td align=center>';
                                       echo substr($relatorio->$getnome(),-2,2); 
                                    }else{                                 
                                        if($relatorio->getsaida() == $relatorio->$getnome()){
                                            echo '<td id="comp" align=right>';
                                            echo '<a title="Clique para ver comprovante" href="'.$relatorio->getcomprovante().'" target="_blank">';
                                                echo number_format($relatorio->$getnome(),2,',','.');
                                            echo '</a>';
                                        }else{
                                            echo '<td align=right>';
                                            echo number_format($relatorio->$getnome(),2,',','.');
                                        }
                                    }
                                 }
                             }elseif(!is_numeric($relatorio->$getnome()) && $relatorio->getdiz_ofe()){
                               if(!in_array($relatorio->getdescricao(),$nomesDupl)){  
                                    if($relatorio->$getnome() == $relatorio->getdiz_ofe()){
                                      echo '<td align=center>';
                                        if($relatorio->getdiz_ofe()=='diz'){
                                           echo 'DIZIMO';
                                        }elseif($relatorio->getdiz_ofe()=='ofe'){
                                           echo 'OFERTA';
                                        }
                                    }elseif($relatorio->$getnome() == $relatorio->getdt()){
                                         echo '<td align=center>';
                                         echo substr($relatorio->$getnome(),8,2);
                                    }else{
                                        echo '<td>';
                                           echo mb_strtoupper($relatorio->$getnome(),'utf-8');
                                    }
                                }else{
                                    if(in_array($relatorio->getdt(),$dataEntrega)){
                                        if(!isset($x))$x=0;
                                        $valorEntregue=$dataEntrega[$nomesD[$x]];
                                        if($nomesD[$x]){
                                            if(!isset($y)){$y=0;}
                                            if(!isset($z)){$z=0;}
                                            if($x!=$y){
                                                echo '<td align="center">'.substr($dataEntrega[$nomesD[$x]],-2,2).'</td><td>'.$nomesD[$x].'</td><td align="right">'.number_format($nomesdiz[$nomesD[$x]],2,',','.').'</td><td></td><td align="center">DIZIMO</td>';
                                                $y=$x;
                                            }elseif($z==0){
                                                echo '<td align="center">'.substr($dataEntrega[$nomesD[$x]],-2,2).'</td><td>'.mb_strtoupper($nomesD[$x],'utf-8').'</td><td align="right">'.number_format($nomesdiz[$nomesD[$x]],2,',','.').'</td><td></td><td align="center">DIZIMO</td>';
                                                $z++;
                                            }
                                        }
                                    }
                                }
                             }elseif($relatorio->$getnome() == $relatorio->getdescricao()){
                                echo '<td align=left>';
                                echo strtoupper($relatorio->$getnome());
                             }else{
                                echo '<td>';
                             }
                             echo '</td>';
                          }
                         if($relatorio->getentrada()!=0){
                             if(!in_array($relatorio->getdescricao(),$nomesD)){
                                $saldo=$saldo+$relatorio->getentrada();
                             }elseif(@in_array($nomesD[$x],$nomesD)){
                                 $saldo=$saldo+$nomesdiz[$nomesD[$x]];
                                 unset($nomesD[$x]);
                                 $x++;
                             }
                                $somaEntrada=$somaEntrada+$relatorio->getentrada();
                         }elseif($relatorio->getsaida()!=0){
                            $saldo=$saldo-$relatorio->getsaida();
                            $somaSaida=$somaSaida+$relatorio->getsaida();
                         }
                            $resumo[]=array('descricao'=>$relatorio->getdescricao(),'saida'=>$relatorio->getsaida(),'entrada'=>$relatorio->getentrada());
                         if(!in_array($relatorio->getdescricao(),$nomesD))
                            echo "<td align=right>".number_format($saldo,'2',',','.')."</td>";
                         echo '</tr>';
                       }
                     ?>   
         </table>
       </div>
           <!-- RESUMO -->
       <div id="printable" class="resumo" >
         <table border="1" cellspacing="0">
           <tr><th colspan="3" align="center">
               MOVIMENTO FINANCEIRO DO MÊS - <?php 
                echo mb_strtoupper($mes,'UTF-8');
                foreach($relatorios as $datas);
                echo '('.$ano.')';
                ?></th></tr>
           <?php $colunas=array('DESCRIÇÃO','SAÍDAS','ENTRADAS');?>
             <tr><?php foreach($colunas as $col)echo "<th>$col</th>";?></tr>
             <?php 
                echo '<tr><td>SALDO ANTERIOR</td><td></td><td align=right>'.number_format($saldoAnterior,'2',',','.').'</td></tr>';
                $ofertas=array();
                $dizimo=array();
                foreach($resumo as $cel){
                   if($cel['saida'] !=0){
                      echo '<tr><td>'.strtoupper($cel['descricao']).'</td><td align=right>'.number_format($cel['saida'],'2',',','.').'</td><td></td></tr>';
                   }elseif($cel['descricao']=='oferta'||$cel['descricao']=='OFERTA'){
                      $ofertas[]=$cel['entrada'];
                   }else{
                      $dizimo[]=$cel['entrada'];
                   }
                }
                echo '<tr><td>OFERTAS</td><td></td><td align=right>'.number_format(array_sum($ofertas),'2',',','.').'</td></tr>';
                echo '<tr><td>DIZIMOS</td><td></td><td align=right>'.number_format(array_sum($dizimo),'2',',','.').'</td></tr>';
                echo '<tr><td align=right>TOTAIS</td><td align=right>'.  number_format($somaSaida,'2',',','.').'</td><td align=right>'.number_format($somaEntrada,'2',',','.').'</td></tr>';
                echo '<tr><td colspan=3 ></td></tr>';
                echo '<tr><td align=right colspan=2>SALDO PARA O MÊS SEGUINTE</td><td align=right>'.number_format($saldoAnterior+$somaEntrada-$somaSaida,'2',',','.').'</td></tr>'; 
                if($conclui==1){
                     $model->setsaldo($saldoAnterior+$somaEntrada-$somaSaida);
                     $model->setano($ano);
                     $model->setmes($mes);
                     $model->settabela('saldo');
                     $dao->grava3($model);
                }           
             ?>
         </table>
         <?php endif; ?>
       </div>
     </div>